name: Routine Environment Setup and Test

# This workflow triggers on push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
  test:
    runs-on: ubuntu-latest  # This sets the virtual machine to Ubuntu

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    # Install dependencies (assumes you have a requirements.txt)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest > 7.0
  

    # Run your tests (you can customize this depending on the test framework you're using)
    - name: Run Tests
      run: |
        pytest  # or any other test command you use
